// Separate grammatical roles keep combinations readable without a language model.
const adjectives = [
  "distant",
  "submerged",
  "pale",
  "forgotten",
  "electric",
  "unlit",
  "slow",
  "hollow",
  "silver",
  "restless",
  "fragile",
  "silent",
  "hidden",
  "frozen",
  "faint",
  "wandering",
  "violet",
  "weightless",
  "broken",
  "sleeping",
  "fading",
  "luminous",
  "unspoken",
  "tender",
  "buried",
  "drifting",
  "porous",
  "velvet",
  "winter",
  "empty",
  "untethered",
  "dust-covered",
  "warm",
  "dissolving",
  "borrowed",
  "soft",
  "doubled",
  "dormant",
  "dusk-blue",
  "transparent",
  "trembling",
  "inverted",
  "dappled",
  "unmapped",
  "interrupted",
  "copper",
  "residual",
  "nocturnal",
  "lucid",
  "nameless",
  "fugitive",
  "overgrown",
];
const objects = [
  "signal",
  "horizon",
  "garden",
  "satellite",
  "memory",
  "harbor",
  "room",
  "window",
  "orchard",
  "station",
  "river",
  "machine",
  "mirror",
  "shore",
  "archive",
  "frequency",
  "threshold",
  "ocean",
  "corridor",
  "constellation",
  "island",
  "observatory",
  "stairwell",
  "antenna",
  "tide",
  "passage",
  "reservoir",
  "lighthouse",
  "transmission",
  "refrain",
  "estuary",
  "interval",
  "monument",
  "weather system",
  "fault line",
  "greenhouse",
  "ribbon",
  "beacon",
  "causeway",
  "orbit",
  "canal",
  "ferry",
  "courtyard",
  "spectrum",
];
const materials = [
  "glass",
  "static",
  "rain",
  "salt",
  "light",
  "ash",
  "moss",
  "mercury",
  "snow",
  "copper",
  "smoke",
  "dust",
  "water",
  "silence",
  "amber",
  "frost",
  "porcelain",
  "neon",
  "mist",
  "gravity",
  "ink",
  "moonlight",
  "sand",
  "lichen",
  "electricity",
  "pollen",
  "tin",
  "quartz",
  "shadow",
  "silt",
  "oxidation",
  "sunlight",
  "ice",
  "rust",
  "steam",
  "chiffon",
];
const plurals = [
  "satellites",
  "windows",
  "islands",
  "stations",
  "echoes",
  "gardens",
  "frequencies",
  "mirrors",
  "ghosts",
  "signals",
  "tides",
  "antennas",
  "footsteps",
  "machines",
  "horizons",
  "shadows",
  "constellations",
  "fragments",
  "rivers",
  "afterimages",
  "dunes",
  "chambers",
  "seasons",
  "strangers",
  "observatories",
  "shorelines",
  "sleepwalkers",
  "sparks",
  "clouds",
  "letters",
  "wires",
  "ferries",
];
const places = [
  "the last station",
  "the flooded city",
  "the empty harbor",
  "the treeline",
  "the polar night",
  "the abandoned observatory",
  "the far shore",
  "the listening room",
  "the glasshouse",
  "the reservoir",
  "the outer ring",
  "the stairwell",
  "the lowlands",
  "the breakwater",
  "the roof garden",
  "the service tunnel",
  "the old transmitter",
  "the salt flats",
  "the departure hall",
  "the orchard",
  "the tidal pools",
  "the north window",
  "the quarry",
  "the estuary",
  "the night ferry",
  "the edge of town",
  "the radio tower",
  "the mountain pass",
  "the winter garden",
  "the underpass",
];
const times = [
  "first light",
  "the thaw",
  "the rain",
  "the last train",
  "daybreak",
  "the power cut",
  "the storm",
  "the long winter",
  "the eclipse",
  "the tide turns",
  "the signal fades",
  "the snow arrives",
  "the city wakes",
  "the lights go out",
  "the birds return",
  "the ferry leaves",
  "the static clears",
  "the room cools",
];
const actions = [
  "dissolves",
  "returns",
  "hesitates",
  "sleeps",
  "gathers",
  "drifts",
  "bends",
  "waits",
  "fractures",
  "settles",
  "recedes",
  "flickers",
  "forgets",
  "lingers",
  "unravels",
  "changes direction",
  "comes apart",
  "finds a way through",
  "moves in circles",
  "loses its shape",
];
const fragments = [
  "nothing stays in focus",
  "we missed the last ferry",
  "there is still time",
  "someone left the radio on",
  "the map ends here",
  "it almost felt familiar",
  "we were only passing through",
  "the lights are still on",
  "you can hear the wires",
  "nobody remembers the route",
  "something moved beneath the ice",
  "we waited for the weather",
  "the room was warmer then",
  "everything arrived out of order",
  "I thought the rain had stopped",
  "the sea is closer now",
  "we left before the thaw",
  "the windows face the water",
  "this used to be a garden",
  "the train did not stop",
  "I kept the receiver open",
  "we came back by another road",
  "the silence had a shape",
  "there was no second signal",
];

export function generateSongName(random: () => number): string {
  const pick = <T>(items: readonly T[]) =>
    items[Math.floor(random() * items.length)];
  const patterns: (() => string)[] = [
    () => `${pick(adjectives)} ${pick(objects)}`,
    () => {
      const first = pick(materials);
      return `${first} and ${pick(materials.filter((x) => x !== first))}`;
    },
    () => `${pick(objects)} of ${pick(materials)}`,
    () => `the ${pick(adjectives)} ${pick(objects)}`,
    () => `between ${pick(adjectives)} ${pick(plurals)}`,
    () => `${pick(plurals)} beneath ${pick(places)}`,
    () => `${pick(materials)} at ${pick(places)}`,
    () => `${pick(adjectives)} ${pick(plurals)} in ${pick(materials)}`,
    () => `where ${pick(materials)} ${pick(actions)}`,
    () => `${pick(objects)} before ${pick(times)}`,
    () => `after ${pick(times)}: ${pick(adjectives)} ${pick(plurals)}`,
    () => `${pick(adjectives)} notes from ${pick(places)}`,
    () => `studies in ${pick(adjectives)} ${pick(materials)}`,
    () => `a place for ${pick(adjectives)} ${pick(plurals)}`,
    () => `${pick(objects)} without ${pick(materials)}`,
    () => `${pick(adjectives)} ${pick(objects)} / ${pick(materials)}`,
    () => `${pick(fragments)}, before ${pick(times)}`,
    () => `when ${pick(materials)} ${pick(actions)}`,
    () => `postcards from ${pick(places)}: ${pick(materials)}`,
    () =>
      `${pick(adjectives)} ${pick(objects)} no. ${1 + Math.floor(random() * 99)}`,
  ];
  const title = pick(patterns)();
  return title.charAt(0).toUpperCase() + title.slice(1);
}
